acoustid/web/views/apps.py
import logging
from flask import Blueprint, render_template, request, redirect, url_for, abort, current_app, session
from acoustid.web import db
from acoustid.web.utils import require_user, is_valid_email, is_valid_url
from acoustid.data.application import find_applications_by_account, insert_application, update_application
from acoustid.data.stats import find_application_lookup_stats

logger = logging.getLogger(__name__)

apps_page = Blueprint('apps', __name__)


@apps_page.route('/applications')
def applications():
    user = require_user()
    title = 'Your Applications'
    applications = find_applications_by_account(db.session.connection(), user.id)
    return render_template('applications.html', title=title,
        applications=applications)


@apps_page.route('/application/<application_id>')
def application(application_id):
    user = require_user()
    title = 'Your Application'
    conn = db.session.connection()
    application = conn.execute("""
        SELECT * FROM application
        WHERE id = %s
    """, (application_id,)).fetchone()
    if application is None:
        abort(404)
    if user.id != application['account_id']:
        abort(404)
    monthly_stats = conn.execute("""
        SELECT
            date_trunc('month', date) AS month,
            sum(count_hits) + sum(count_nohits) AS lookups
        FROM stats_lookups
        WHERE application_id = %s
        GROUP BY date_trunc('month', date)
        ORDER BY date_trunc('month', date)
    """, (application_id,)).fetchall()
    lookups = find_application_lookup_stats(conn, application_id)
    return render_template('application.html', title=title,
        app=application, monthly_stats=monthly_stats, lookups=lookups)


@apps_page.route('/new-application', methods=['GET', 'POST'])
def new_application():
    user = require_user()
    errors = []
    title = 'New Application'
    if request.form.get('submit'):
        name = request.form.get('name')
        if not name:
            errors.append('Missing application name')
        version = request.form.get('version')
        if not version:
            errors.append('Missing version number')
        email = request.form.get('email')
        if email and not is_valid_email(email):
            errors.append('Invalid email address')
        website = request.form.get('website')
        if website and not is_valid_url(website):
            errors.append('Invalid website URL')
        if not errors:
            insert_application(db.session.connection(), {
                'name': name,
                'version': version,
                'email': email,
                'website': website,
                'account_id': user.id,
            })
            db.session.commit()
            return redirect(url_for('.applications'))
    return render_template('new-application.html', title=title,
        form=request.form, errors=errors)



@apps_page.route('/application/<application_id>/edit', methods=['GET', 'POST'])
def edit_application(application_id):
    user = require_user()
    conn = db.session.connection()
    application = conn.execute("""
        SELECT * FROM application
        WHERE id = %s
    """, (application_id,)).fetchone()
    if application is None:
        abort(404)
    if user.id != application['account_id']:
        abort(404)
    errors = []
    title = 'Edit Applications'
    if request.form.get('submit'):
        form = request.form
        name = request.form.get('name')
        if not name:
            errors.append('Missing application name')
        version = request.form.get('version')
        if not version:
            errors.append('Missing version number')
        email = request.form.get('email')
        if email and not is_valid_email(email):
            errors.append('Invalid email address')
        website = request.form.get('website')
        if website and not is_valid_url(website):
            errors.append('Invalid website URL')
        if not errors:
            update_application(conn, application.id, {
                'name': name,
                'version': version,
                'email': email,
                'website': website,
                'account_id': user.id,
            })
            db.session.commit()
            return redirect(url_for('.applications'))
    else:
        form = {}
        form['name'] = application['name']
        form['version'] = application['version'] or ''
        form['email'] = application['email'] or ''
        form['website'] = application['website'] or ''
    return render_template('edit-application.html', title=title,
        form=form, errors=errors, app=application)

acoustid/web/views/stats.py
# Copyright (C) 2011, 2015 Lukas Lalinsky
# Distributed under the MIT license, see the LICENSE file for details.

import logging
from flask import Blueprint, render_template, request, redirect, url_for, abort, current_app
from acoustid.web import db
from acoustid.data.stats import (
    find_current_stats,
    find_daily_stats,
    find_lookup_stats,
    find_application_lookup_stats,
)

logger = logging.getLogger(__name__)

stats_page = Blueprint('stats', __name__)


def percent(x, total):
    if total == 0:
        x = 0
        total = 1
    return '%.2f' % (100.0 * x / total,)


def prepare_pie_chart_data(stats, pattern):
    track_mbid_data = []
    track_mbid_sum = 0
    for i in range(11):
        value = stats.get(pattern % i, 0)
        if i != 0:
            track_mbid_sum += value
        track_mbid_data.append(value)
    track_mbid = []
    for i, count in enumerate(track_mbid_data):
        if i == 0:
            continue
        track_mbid.append({
            'i': i,
            'count': count,
            'percent': percent(count, track_mbid_sum),
        })
    return track_mbid


@stats_page.route('/stats')
def stats():
    title = 'Statistics'
    stats = find_current_stats(db.session.connection())
    basic = {
        'submissions': stats.get('submission.all', 0),
        'fingerprints': stats.get('fingerprint.all', 0),
        'tracks': stats.get('track.all', 0),
        'mbids': stats.get('mbid.all', 0),
        'contributors': stats.get('account.active', 0),
    }
    track_mbid = prepare_pie_chart_data(stats, 'track.%dmbids')
    mbid_track = prepare_pie_chart_data(stats, 'mbid.%dtracks')
    basic['tracks_with_mbid'] = basic['tracks'] - stats.get('track.0mbids', 0)
    basic['tracks_with_mbid_percent'] = percent(basic['tracks_with_mbid'], basic['tracks'])
    daily_raw = find_daily_stats(db.session.connection(), ['track.all', 'mbid.all'])
    daily = {
        'tracks': daily_raw['track.all'],
        'mbids': daily_raw['mbid.all'],
    }
    lookups = find_lookup_stats(db.session.connection())
    return render_template('stats.html', title=title, basic=basic,
        track_mbid=track_mbid, mbid_track=mbid_track,
        daily=daily, lookups=lookups)

acoustid/web/templates/_base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" dir="ltr"> 
<head> 
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
	<title>{% if title %}{{ title }} | {% endif %}AcoustID</title> 
	<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}" /> 
	<script type="text/javascript" src="{{ url_for('static', filename='jquery-1.10.0.min.js') }}"></script>
	<script type="text/javascript"> 
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18981078-1']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
 
	</script> 
</head> 
<body style="margin-top:0;"> 
        {# <div style="text-align: center; width:100%; font-weight: bold; font-size:130%; color:red;">The AcoustID website is currently in read-only mode for maintenance.</div> #}
        {# <div style="text-align: left; width:100%; font-size: 14px; background-color: #ffefd7; padding:10px; font-weight: bold;">

<div style="width:740px; margin-left:auto; margin-right:auto; position:relative; padding-right:120px;">

Dear users &mdash;
AcoustID provides free service to a number of open source applications.
If you are using such an application and find AcoustID useful, please consider donating a
small amount, to keep it running smoothly and stay free.
<i>Thank you.</i>

<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" style="position:absolute; right:10px; top:5px;">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="RRBS25ADWPK2E">
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>

</div> #}

	</div>
	<div id="container"> 
		<div id="container-inner"> 
			<h1><a href="{{ url_for('general.index') }}" title="AcoustID"><span>AcoustID</span></a></h1> 
			<ul id="menu"> 
				<li><a href="{{ url_for('user.api_key') }}"><strong>Get API Key</strong></a></li> 
				{% if account_id  %}
				<li><a href="{{ url_for('apps.applications') }}">Applications</a></li> 
				<li><a href="{{ url_for('user.logout') }}">Log out</a></li> 
				{% endif %}
				<li><a href="{{ url_for('stats.stats') }}">Statistics</a></li> 
				<li><a href="{{ url_for('general.docs') }}">Documentation</a></li> 
				<li><a href="{{ url_for('general.donate') }}">Donate</a></li> 
				<li><a href="https://oxygene.sk/category/acoustid/">Blog</a></li> 
				<li><a href="https://groups.google.com/forum/#!forum/acoustid">Mailing List</a></li> 
			</ul> 
			<div id="content"> 
            {% block content %}{% endblock %}
			</div> 
		</div> 
	</div> 
	<p id="footer"> 
		Created by <a href="https://oxygene.sk/">Lukáš Lalinský</a> |
		<a href="http://status.acoustid.org">Status</a> |
		<a href="{{ url_for('general.license') }}">License</a> |
		<a href="{{ url_for('general.donate') }}">Donate</a> |
		<a href="{{ url_for('general.contact') }}">Contact</a> |
		<a href="https://twitter.com/acoustid">Twitter</a> |
		<a href="https://www.facebook.com/acoustid">Facebook</a>
	</p> 
</body> 
</html> 
 

acoustid/web/templates/application.html
{% extends "_base.html" %}
{% block content %}

<h2>Application "{{ app.name }}"</h2>

<p><b>Details</b> (<a href="{{ url_for('.edit_application', application_id=app.id) }}">edit</a>)</p>

<ul>
    <li><b>Version:</b> {{  app.version }}</li>
    <li><b>Email:</b> {% if app.email %}<a href="mailto:{{ app.email }}">{{ app.email }}</a>{% else %}none{% endif %}</li>
    <li><b>Website:</b> {% if app.website %}<a href="{{ app.website }}">{{ app.website }}</a>{% else %}none{% endif %}</li>
</ul>

<p><b>Searches during the last 30 days</b></p>

<div id="lookups-graph-fp"></div>

<p><b>Searches per month</b></p>

<table class="listing">
    {% for m in monthly_stats %}
    <tr>
        <td>{{ m.month.strftime('%B %Y') }}</td>
        <td class="r">{{ m.lookups }}</td>
    </tr>
    {% endfor %}
</table>

{% macro lookup_data_series(name, data, field, visible=True)  %}
{
    name: '{{ name }}',
	data: [
		{% for i in data -%}
			[Date.UTC({{ i.date.year }}, {{ i.date.month - 1 }}, {{ i.date.day }}), {{ i[field] }}]{% if not loop.last %},{% endif %}
		{%- endfor %}
	],
	visible: {{ 'true' if visible else 'false' }}
}
{% endmacro %}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" type="text/javascript"></script>
<script src="/static/highcharts.js" type="text/javascript"></script>
<script type="text/javascript">
var chart1; // globally available
var chart2; // globally available
$(document).ready(function() {
	chart2 = new Highcharts.Chart({
		chart: {
			renderTo: 'lookups-graph-fp',
			height: 250,
			zoomType: 'x',
			defaultSeriesType: 'line'
		},
		title: { text: '' },
		xAxis: {
			type: 'datetime',
			dateTimeLabelFormats: {
				month: '%e. %b',
				year: '%b'
			}
		},
		yAxis: {
			title: { text: '' }
		},
		legend: {
			shadow: false
		},
		plotOptions: {
			line: {
				lineWidth: 1
			}
		},
		series: [
			{{ lookup_data_series('All', lookups, 'count') }},
			{{ lookup_data_series('Hits', lookups, 'count_hits') }},
			{{ lookup_data_series('Misses', lookups, 'count_nohits') }}
		]
	});
});
</script>


{% endblock %}

acoustid/web/templates/applications.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

{% if applications %}

<p>
	If you are the developer of an application that uses the AcoustID web service, please register your application.
	So far you've registered the following applications:
</p>

<table class="apps">
<thead>
	<tr>
		<th>Name</th>
		<th>Version</th>
		<th>API Key</th>
	</tr>
</thead>
<tbody>
{% for app in applications %}
	<tr>
		<td><a href="{{ url_for('.application', application_id=app.id) }}">{{ app.name }}</a></td>
		<td>{{ app.version }}</td>
		<td><code>{{ app.apikey }}</code></td>
	</tr>
{% endfor  %}
</tbody>
</table>

{% else %}

<p>
	You do not have any registered applications. If you are the developer of an application that uses the AcoustID web service, please register your application.
</p>

{% endif %}

<p class="center">
	<a href="{{ url_for('.new_application') }}">Register a new application</a>
</p>

{% endblock %}

acoustid/web/templates/compare_fingerprints.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

<p>
  <button id="move-up">Move Up</button>
  <button id="move-down">Move Down</button>
  Offset: <span id="offset">0</span>
</p>

<p><canvas style="border: solid 2px #C5C5C5;" id="fp-img" width="32" height="0"></canvas></p>

<p>
  Back to <a href="{{ url_for('.fingerprint', fingerprint_id=fingerprint_1.id) }}">fingerprint #{{ fingerprint_1.id }}</a>
  or <a href="{{ url_for('.fingerprint', fingerprint_id=fingerprint_2.id) }}">fingerprint #{{ fingerprint_2.id }}</a>
</p>

<script type="text/javascript" src="{{ url_for('static', filename='fputils.js') }}"></script>
<script type="text/javascript">
$(document).ready(function () {
   var fp1 = {{ fingerprint_1.fingerprint }};
   var fp2 = {{ fingerprint_2.fingerprint }};
   var canvas = document.getElementById('fp-img');
   var offset = 0;

   function repaint() {
       paintFingerprintDiff(canvas, fp1, fp2, offset);
       $("#offset").text(offset);
   }

   repaint();

   $('#move-up').click(function () {
       offset -= 1;
       repaint();
   });

   $('#move-down').click(function () {
       offset += 1;
       repaint();
   });

});
</script>

{% endblock %}

acoustid/web/templates/edit-application.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2> 

{% if errors %}
<p class="errors">{% for error in errors %}{{ error }}<br />{% endfor %}</p>
{% endif %}

<form action="{{ url_for('.edit_application', application_id=app.id) }}" method="POST"> 
<p>
	<small><label for="name_i">Application name:</label></small><br />
 	<input name="name" id="name_i" type="text" class="text" value="{{ form.name }}" /><br />
	<small><label for="version_i">Version number:</label></small><br />
	<input name="version" id="version_i" type="text" class="text" value="{{ form.version }}" /><br />
	<small><label for="email_i">Contact email: <small>(optional)</small></label></small><br />
 	<input name="email" id="email_i" type="text" class="text" value="{{ form.email }}" /><br />
	<small><label for="website_i">Website: <small>(optional)</small></label></small><br />
 	<input name="website" id="website_i" type="website" class="text" value="{{ form.website }}" /><br />
</p>
<p>
	<input type="submit" value="Register" />
	<input type="hidden" name="submit" value="1" />
</p>
</form>

{% endblock %}

acoustid/web/templates/fingerprint.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

<p><canvas style="border: solid 2px #C5C5C5;" id="fp-img" width="32" height="0"></canvas></p>

<p>Compare with another fingerprint <input id="fp_id" size="6" placeholder="ID"/> <button id="compare">Compare</button></p>

<p>Back to <a href="{{ url_for('.track', track_id=track_gid) }}">track "{{ track_gid }}"</a></p>

<script type="text/javascript" src="{{ url_for('static', filename='fputils.js') }}"></script>
<script type="text/javascript">
$(document).ready(function () {
   var fp = {{ fingerprint.fingerprint }};
   var canvas = document.getElementById('fp-img');
   paintFingerprint(canvas, fp);

   $('#compare').click(function () {
       var id2 = $('#fp_id').val();
       var url = '/fingerprint/{{ fingerprint.id }}/compare/' + id2;
       window.location.href = url;
   });
});
</script>

{% endblock %}

acoustid/web/templates/login.html
{% extends "_base.html" %}
{% block content %}

<script type="text/javascript"> 
$(document).ready(function () {
    $('.login-musicbrainz').click(function () {
        var $form = $(this).closest('form');
        $form.find('input[name=login]').val('musicbrainz');
        $form.submit();
        return false;
    });
    $('.login-google').click(function () {
        var $form = $(this).closest('form');
        $form.find('input[name=login]').val('google');
        $form.submit();
        return false;
    });
    $('.login-yahoo').click(function () {
        var $form = $(this).closest('form');
        $form.find('input[name=login]').val('openid');
        $form.find('input.openid').val('https://me.yahoo.com');
        $form.submit();
        return false;
    });
    $('.login-openid').click(function () {
        var $this = $(this), $form = $this.closest('form');
        $this.addClass('active');
        $form.find('input[name=login]').val('openid');
        $form.find('.openid-form').show();
        $form.find('.openid-form input.openid').focus();
        return false;
    });
});
</script> 

<h2>Log In</h2> 

{% if errors %}
<p class="errors">{% for error in errors %}{{ error }}<br />{% endfor %}</p>
{% endif %}

<p><small>Please log in with an account from one of these providers:</small></p>

<form action="{{ url_for('.login') }}" method="POST"> 

<p>
    <a class="login-block login-musicbrainz" href="#"><span>Log in with MusicBrainz</span></a>
    <a class="login-block login-google" href="#"><span>Log in with Google</span></a>
    <a class="login-block login-yahoo" href="#"><span>Log in with Yahoo!</span></a>
    <a class="login-block login-openid" href="#"><span>Log in with OpenID</span></a>
</p>

<p class="openid-form" style="display:none">
    <input name="openid_identifier" type="text" class="openid" /> <input type="submit" value="Log in" />
</p>

<input type="hidden" name="return_url" value="{{ return_url }}" /> 
<input type="hidden" name="login" value="openid" /> 

</form> 

{% endblock %}

acoustid/web/templates/mbid-not-found.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

<p>
    There is no MusicBrainz recording with ID {{ mbid }}.
</p>

{% endblock %}

acoustid/web/templates/mbid.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

<p>
    See more information about this recording on
    <a href="//musicbrainz.org/track/{{ mbid }}">MusicBrainz</a>.
</p>

{% if tracks %}

<p>Linked tracks:</p>

<ul>
{% for tr in tracks %}
    <li><a href="{{ url_for('.track', track_id=tr.id) }}">{{ tr.gid }}</a></li>
{% endfor %}
</ul>

{% endif %}

{% endblock %}

acoustid/web/templates/new-application.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2> 

{% if errors %}
<p class="errors">{% for error in errors %}{{ error }}<br />{% endfor %}</p>
{% endif %}

<form action="{{ url_for('.new_application') }}" method="POST"> 
<p>
	<small><label for="name_i">Application name:</label></small><br />
 	<input name="name" id="name_i" type="text" class="text" value="{{ form.name }}" /><br />
	<small><label for="version_i">Version number:</label></small><br />
	<input name="version" id="version_i" type="text" class="text" value="{{ form.version }}" /><br />
	<small><label for="email_i">Contact email: <small>(optional)</small></label></small><br />
 	<input name="email" id="email_i" type="text" class="text" value="{{ form.email }}" /><br />
	<small><label for="website_i">Website: <small>(optional)</small></label></small><br />
 	<input name="website" id="website_i" type="website" class="text" value="{{ form.website }}" /><br />
</p>
<p>
	<input type="submit" value="Register" />
	<input type="hidden" name="submit" value="1" />
</p>
</form>

{% endblock %}

acoustid/web/templates/stats.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

<p><b>Basic statistics</b></p>

<table class="listing">
    <tr>
        <td>AcoustIDs</td>
        <td class="r">{{ basic.tracks }}</td>
    </tr>
    <tr>
        <td>Fingerprints</td>
        <td class="r">{{ basic.fingerprints }}</td>
    </tr>
    <tr>
        <td>Recordings</td>
        <td class="r">{{ basic.mbids }}</td>
    </tr>
    <tr>
        <td>Contributors</td>
        <td class="r">{{ basic.contributors }}</td>
    </tr>
</table>

<p><b>Daily additions</b></p>

<div id="graph-fp"></div>

<p><b>Searches</b></p>

<div id="lookups-graph-fp"></div>

<p><b>AcoustIDs per the number of linked recordings</b></p>

<table class="listing">
    <tr>
        <td>AcoustIDs with at least 1 recording</td>
        <td class="r">{{ basic.tracks_with_mbid }}</td>
        <td class="r">{{ basic.tracks_with_mbid_percent }} %</td>
    </tr>
    {% for t in track_mbid %}
    <tr class="indent">
        <td>with {% if t.i == 1 %}1 recording{% elif t.i == 10 %}10 or more recordings{% else %}{{ t.i }} recordings{% endif %}</td>
        <td class="r">{{ t.count }}</td>
        <td class="r">{{ t.percent }} %</td>
    </tr>
    {% endfor %}
</table>

<p><b>Recordings per the number of linked AcoustIDs</b></p>

<table class="listing">
    <tr>
        <td>Recording with at least 1 AcoustID</td>
        <td class="r">{{ basic.mbids }}</td>
        <td class="r">100.00 %</td>
    </tr>
    {% for t in mbid_track %}
    <tr class="indent">
        <td>with {% if t.i == 1 %}1 AcoustID{% elif t.i == 10 %}10 or more AcoustIDs{% else %}{{ t.i }} AcoustIDs{% endif %}</td>
        <td class="r">{{ t.count }}</td>
        <td class="r">{{ t.percent }} %</td>
    </tr>
    {% endfor %}
</table>

{% macro data_series(name, data, visible=True)  %}
{
    name: '{{ name }}',
	data: [
		{% for i in data -%}
			[Date.UTC({{ i.date.year }}, {{ i.date.month - 1 }}, {{ i.date.day }}), {{ i.value }}]{% if not loop.last %},{% endif %}
		{%- endfor %}
	],
	visible: {{ 'true' if visible else 'false' }}
}
{% endmacro %}

{% macro lookup_data_series(name, data, field, visible=True)  %}
{
    name: '{{ name }}',
	data: [
		{% for i in data -%}
			[Date.UTC({{ i.date.year }}, {{ i.date.month - 1 }}, {{ i.date.day }}), {{ i[field] }}]{% if not loop.last %},{% endif %}
		{%- endfor %}
	],
	visible: {{ 'true' if visible else 'false' }}
}
{% endmacro %}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" type="text/javascript"></script>
<script src="/static/highcharts.js" type="text/javascript"></script>
<script type="text/javascript">
var chart1; // globally available
var chart2; // globally available
$(document).ready(function() {
	chart1 = new Highcharts.Chart({
		chart: {
			renderTo: 'graph-fp',
			height: 250,
			zoomType: 'x',
			defaultSeriesType: 'line'
		},
		title: { text: '' },
		xAxis: {
			type: 'datetime',
			dateTimeLabelFormats: {
				month: '%e. %b',
				year: '%b'
			}
		},
		yAxis: {
			title: { text: '' }
		},
		legend: {
			shadow: false
		},
		plotOptions: {
			line: {
				lineWidth: 1
			}
		},
		series: [
			{{ data_series('AcoustIDs', daily.tracks) }},
			{{ data_series('MBIDs', daily.mbids) }},
		]
	});
	chart2 = new Highcharts.Chart({
		chart: {
			renderTo: 'lookups-graph-fp',
			height: 250,
			zoomType: 'x',
			defaultSeriesType: 'line'
		},
		title: { text: '' },
		xAxis: {
			type: 'datetime',
			dateTimeLabelFormats: {
				month: '%e. %b',
				year: '%b'
			}
		},
		yAxis: {
			title: { text: '' }
		},
		legend: {
			shadow: false
		},
		plotOptions: {
			line: {
				lineWidth: 1
			}
		},
		series: [
			{{ lookup_data_series('All', lookups, 'count') }},
			{{ lookup_data_series('Hits', lookups, 'count_hits') }},
			{{ lookup_data_series('Misses', lookups, 'count_nohits') }}
		]
	});
});
</script>

{% endblock %}

acoustid/web/templates/toggle_track_mbid_login.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

<p>We are sorry, but editing is only possible if you log in with a MusicBrainz account.</p>

{% endblock %}

acoustid/web/templates/track-not-found.html
{% extends "_base.html" %}
{% block content %}

<h2>{{ title }}</h2>

<p>
    There is no track with ID {{ track_id }} in the AcoustID database.
</p>

{% endblock %}